#include <exception>

class InvaildInput : public std::exception {
 private:
  const char * error_msg;

 public:
  InvaildInput(const char * msg) : error_msg(msg) {}
  InvaildInput() : error_msg("Invaild input.") {}
  virtual const char * what() const throw() { return error_msg; }
};
